name: Python ContinuosIntegration
 
on:
  pull_request:
    branches:
      - main
jobs:
  python-build:
 
    runs-on: ubuntu-latest
    env:
      DOTENV_FILE: ${{ secrets.ENV_FILE }}
      GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set to your Python version
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GCP_CREDENTIALS_JSON }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create .env file
      id: create_env_file
      run: |
          echo "$DOTENV_FILE" > .env
    - name: Check code
      run: |
        python -m compileall -q .